block: model.ae_variational
params:
  encoder_layers: [128, 64]
  latent_dim: 16
  decoder_layers: [64, 128]
  learning_rate: 0.001
  batch_size: 64
  max_epochs: 100
  dropout: 0.2
  weight_decay: 1e-5
  beta: 1.0 # KL divergence weight
  normalize_inputs: true
