block: model.random_forest
params:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: "sqrt"
  bootstrap: true
  random_state: 42
  n_jobs: -1
  class_weight: null # Use "balanced" for imbalanced datasets
  criterion: "gini"
